### ISSUE TITLE
Problem with using drawViewHierarchyInRect: instead renderInContext:

### ISSUE THREAD

**Issue by ArtFeel** [evadne/LiveFrost#10]
Hello, I'm trying to increase performance of live blur on iOS7, so i changed this code:

``` objective-c
- (void) refresh {
    //   . . .
    self.hidden = YES;
    [self.superview.layer renderInContext:effectInContext];
    self.hidden = NO;
    //   . . .
}
```

into this:

``` objective-c
- (void) refresh {
    //   . . .
    self.hidden = YES;
    UIGraphicsPushContext(effectInContext);
    [self.superview drawViewHierarchyInRect:self.superview.bounds afterScreenUpdates:NO];
    UIGraphicsPopContext();
    self.hidden = NO;
    //   . . .
}
```

But, `setHidden` property is not working, because I don't wait for screen update, and GlassView blurred itself =). If I set `afterScreenUpdates:YES` performance becomes even worse than it was when I use `renderInContext:`. Maybe you know how to properly hide glassView from current context?

**Comment by ghost** [comment]
There is a reason why we use `-renderInContext:` instead; for this purpose, it's faster, and it works better than the alternatives.

`-renderInContext:` renders directly from a `CALayer`'s render tree to valid Core Graphics context. It's not perfect, it won't render layers that render directly to the GPU's hardware compositor (`CAEAGLlayer`s and `AVPlayerLayer`s both have this limitation), and it naively assumes that the transformation matrix applied to the `CALayer` object (via the `transform` ivar) is an identity matrix. I assume it does these things to stay fast, and avoid forcing content that would normally render directly to the hardware compositor to copy its contents to a byte buffer so that their contents can be read in software.

iOS 7 introduced `-snapshotViewAfterScreenUpdates:` and several related methods such as `-drawViewHierarchyInRect:afterScreenUpdates:`. It seems that they were made to accommodate the new backgrounding/foregrounding behavior for iOS 7. And while the documentation says quite a bit about how fast these methods are, there's a really big limitation to that.

You need to set `...afterScreenUpdates:` to YES to get a proper byte buffer without any delay into a Core Graphics context. Without that byte buffer, there's no way of properly blurring the view through the Accelerate framework, or through any means that takes advantage of the NEON co-processor. And as you've seen, that delay causes things to render much, much slower.

Even if you're doing nothing else but blurring the view at 60 frames per second, the performance hit of calling that method with `...afterScreenUpdates:` set to `YES` is absolutely unacceptable on an iPhone 4.

Now, even if we could figure out a way to blur with `afterScreenUpdates:` set to `NO`, what we'd have would be a byte buffer that would be delayed by at least one frame from the content that we're trying to blur. That's exactly why we chose not to blur from another thread, or by any means that required delaying rendering of the source view to the blurred destination. That delay is really distracting, and totally breaks the illusion of frosted glass when the blurring is stuck in the past.

My impression is that these methods are fantastic for screenshot capture, like you see in iOS 7, but they weren't made with any sort of elaborate, real time rendering in mind.

Maybe that will change for iOS 8? We can hope.

It might even be worthwhile to file a radar requesting that Apple give us an asynchronous `-afterScreenUpdates:` completion BLOCK instead of this dinky `BOOL`ean value. The API is a bit hard to work with, in its current form.

I don't think that would get rid of the potential lag that I've described, but it would be an improvement.

The best option of all to avoid any sort of lag would be to be able to apply OpenGL ES2 shaders directly to a `CALayer`'s contents so we could avoid having to copy it to a CPU managed byte buffer where the buffer is passed back into the GPU through GL as a texture. That, too, would be a piece of API that I'd love to have, but will probably never happen.

**Comment by ArtFeel** [comment]
Thank you for such detailed response :+1: 

Now, I'm trying to implement custom `modalViewController` with `LFGlassView` at the background. And I have a performance problems when keyboard appears on the screen. Maybe I can tweak `CADisplayLink` a bit, experiment with `frameInterval` or even `paused` notifications manually after all animations finished.

**Comment by ghost** [comment]
I'm going to close this, but we might want to revisit `-drawViewHierarchyInRect:` later. I don't see it as a full replacement for `-renderInContext:`, but its got some interesting qualities.

Maybe after that layer-based refactoring is taken care of and we have a solid API in place that provides an alternative to blurring the superview, we can look into adding more options like this.
