### ISSUE TITLE
Use LiveFrost to do non-live blurring?

### ISSUE THREAD

**Issue by Shukuyen** [evadne/LiveFrost#11]
The name of the project probably answers my question, but hey ...
Is it possible to use LiveFrost to do a single blur on a view hierarchy? I really like your implementation and the speed of it, but I don't need my blur to be refreshed. To save ressources I would like to have it blurred once until I tell it to do it again (for example when the image of an imageview changes).

Thanks!

**Comment by ArtFeel** [comment]
You can disable live blurring. Look at [this issue](https://github.com/radi/LiveFrost/issues/3#issuecomment-32107641) for more information.

**Comment by Shukuyen** [comment]
Thanks for your answer. I saw that issue and tried the `liveBlurring` property, but once you disable that blurring will stop altogether (which makes sense considering the focus of this project). There is no "stop live blurring but keep last blurred state" option as far as I can see.

**Comment by ghost** [comment]
`liveBlurring` does keep the last blurred state, but you need for the view's bounds to have a `width` and `height` that is not `0`, and to have been displayed on screen with `liveBlurring` set to `YES` before you set it to `NO`. Or if not displayed on screen, then to have been attached to a view that belongs to a `UIWindow`'s view hierarchy, as of the `HEAD` of `develop`.

If it doesn't do exactly what I've described for some code that you've written, please let me know immediately because that is certainly a bug!

It's easier to explain when you see the [implementation](https://github.com/radi/LiveFrost/blob/dac9abd33d4b4fe11a009bc34552743e222004df/LiveFrost/LFGlassView.m#L175) of `-isReadyToLiveBlur`. On `develop`, there's now four things to check, one of which is a user defined ivar that holds onto the state the developer specified from `-setLiveBlurring:`, which is `_shouldLiveBlur`. The other three bits to check, if one happens to be false, would cause the `CALayer`'s `-renderInContext:` method to complain very loudly or crash if we tried blurring right then because at that point, the view hierarchy can't be drawn.

I suppose it couldn't hurt to add an instance method that ignores `_shouldLiveBlur`. Can't quite think of a good name at the moment, maybe `-blurIfPossible`? :frowning: There is actually an `NSDiscardableContent` protocol that has an instance method named like that.

I can add that to `develop` right now before I kick off another Cocoapods release on Friday, so you can try it out. If there are no further objections to the name.

**Comment by ghost** [comment]
Just added `-blurIfPossible` to `develop` in https://github.com/radi/LiveFrost/commit/de46ca47bd5d32818297ef0f62f12cd42e0bf0ea. _EDIT:_ And checked for the right thing in https://github.com/radi/LiveFrost/commit/98ece13f77d63f5c1fcc841aeab3951c23823ca4 , whoops.

If this is a really terrible idea, you have until Friday to let me know.

**Comment by ghost** [comment]
Going a step further, this method is called `-blurOnceIfPossible` in https://github.com/radi/LiveFrost/commit/59ae4094aa02370ed19a02cdc619cb7938e70e3c, to avoid any suggestion that this method needs to be called before or when you're in the middle of live blurring.

**Comment by ghost** [comment]
I'm going to have to recommend that you check the HEAD for the latest changes from now on, because I don't want to spam anybody watching this repo. :)

As of https://github.com/radi/LiveFrost/commit/152a64c4e2083ab739f3e8ae469da734fb16e95a , I'm electing to check the presentation layer, because that's probably the most rock solid reliable ivar to tell when it's okay to blur.

Let me know if you run into any issues with this. I'll help out however I can.

**Comment by Shukuyen** [comment]
Thanks a lot for looking into this, will test asap!

**Comment by Shukuyen** [comment]
It's working. I just need to make sure the view is already added to the hierarchy. In my case (displaying a blurred background image) I set the imageView alpha to 0, set the image and add the LFGlassView subview. Then I animate the alpha to 1 and turn off liveBlurring in the UIView animation completion block.

**Comment by ArtFeel** [comment]
@nglevin Nice job :+1: 
I just updated my project to the latest stable version and all works as expected!
