### ISSUE TITLE
TouchEvents not Working

### ISSUE THREAD

**Issue by fabnoe** [evadne/LiveFrost#16]
I assigned "LFGlassView" to the root View in Storyboard. Than I put a Button on top of this view --> but not touch events are fired.

What's wrong? Using just UIView works perfect.

**Comment by ghost** [comment]
Do you know what `userInteractionEnabled` is? It's in [the documentation](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIView_Class/UIView/UIView.html#//apple_ref/occ/instp/UIView/userInteractionEnabled), which unfortunately I can't give you a direct link to so you'll have to scroll down to see it.

It's one of the defaults, it's [set to `NO`](https://github.com/radi/LiveFrost/blob/782e8a46e77064c1bd03ccccddf78daf30ef47e7/LiveFrost/LFGlassView.m#L77) so that touches can be intercepted instead by the view below.

If you just assign the `LFGlassView`'s `userInteractionEnabled` a value of `YES`, it along with all subviews will receive touch events.

We did undo one of the defaults because it was mildly unpopular in response to issue #12 . We could do that here, too.

**Comment by evadne** [comment]
It is probably your view hierarchy, as LFGlassView is not designed to work with subviews within it.

**Comment by ghost** [comment]
Another alternative besides changing defaults would be to work with the `-hitTest:withEvent:` callback to [return `nil`](http://cocoaheads.tumblr.com/post/2130871776/ignore-touches-to-uiview-subclass-but-not-to-its) if the hit test returns the glass view, instead of one of its subviews.

That's actually a much safer change, I could add that to `develop` and see if it does what you want.

**Comment by ghost** [comment]
On _second thought_, if I do add that to `develop`, then that's harder to turn off than switching off the ivar.

We could add a separate ivar to determine if the hit test override should happen. Let me put that on develop and you can see if that suits your needs.

**Comment by ghost** [comment]
Give https://github.com/radi/LiveFrost/commit/9e96a5be04ff2cfbd4e8cbd82fd22fe218db2835 a try, on `develop`. You shouldn't have to change any ivars, the defaults should work in your favor.

**Comment by fabnoe** [comment]
Thanks so much. I tried to enable userInteractionEnabled via Interfacebuilder – which did not work. Now I added this line to my vc  

```
self.view.userInteractionEnabled = YES;
```

**Comment by ghost** [comment]
Did you try pulling from the latest code on the develop branch?

You shouldn't need to do anything special for `-viewDidLoad`. If you did, I'll roll back that change, because that's not right.

**Comment by ghost** [comment]
Without confirmation, I've reverted all commits that were related to this ticket. If someone would want this feature back in, let me know.

**Comment by evadne** [comment]
I think you should just use the glass view as the root view, but turn user interaction on. This will work because the glass view hides itself before capture and re-shows itself after capture. (A more proper way is probably to selectively render layers from the bottom up once we have ability to walk the tree and convert layer hierarchies to absolute depth numbers, but that’s for another day.)
